# Generated by ops_gen.py on Thu Nov 13 11:19:35 2014
from mnt3_const import *
from mnt3_type import *

class MNT3Operations:

    def null_op(self):
        return mnt_argop3(argop=MOUNTPROC3_NULL)

    def mnt_op(self):
        return mnt_argop3(argop=MOUNTPROC3_MNT)

    def dump_op(self):
        return mnt_argop3(argop=MOUNTPROC3_DUMP)

    def umnt_op(self):
        return mnt_argop3(argop=MOUNTPROC3_UMNT)

    def umntall_op(self):
        return mnt_argop3(argop=MOUNTPROC3_UMNTALL)

    def export_op(self):
        return mnt_argop3(argop=MOUNTPROC3_EXPORT)
