# Generated by ops_gen.py on Thu Nov 13 11:19:35 2014
from nfs3_const import *
from nfs3_type import *

class NFS3Operations:

    def null_op(self):
        return nfs_argop3(argop=NFSPROC3_NULL)

    def getattr_op(self, object):
        args = GETATTR3args(object)
        return nfs_argop3(argop=NFSPROC3_GETATTR, opgetattr=args)

    def setattr_op(self, object, new_attributes, guard):
        args = SETATTR3args(object, new_attributes, guard)
        return nfs_argop3(argop=NFSPROC3_SETATTR, opsetattr=args)

    def lookup_op(self, what):
        args = LOOKUP3args(what)
        return nfs_argop3(argop=NFSPROC3_LOOKUP, oplookup=args)

    def access_op(self, object, access):
        args = ACCESS3args(object, access)
        return nfs_argop3(argop=NFSPROC3_ACCESS, opaccess=args)

    def readlink_op(self, symlink):
        args = READLINK3args(symlink)
        return nfs_argop3(argop=NFSPROC3_READLINK, opreadlink=args)

    def read_op(self, file, offset, count):
        args = READ3args(file, offset, count)
        return nfs_argop3(argop=NFSPROC3_READ, opread=args)

    def write_op(self, file, offset, count, stable, data):
        args = WRITE3args(file, offset, count, stable, data)
        return nfs_argop3(argop=NFSPROC3_WRITE, opwrite=args)

    def create_op(self, where, how):
        args = CREATE3args(where, how)
        return nfs_argop3(argop=NFSPROC3_CREATE, opcreate=args)

    def mkdir_op(self, where, attributes):
        args = MKDIR3args(where, attributes)
        return nfs_argop3(argop=NFSPROC3_MKDIR, opmkdir=args)

    def symlink_op(self, where, symlink):
        args = SYMLINK3args(where, symlink)
        return nfs_argop3(argop=NFSPROC3_SYMLINK, opsymlink=args)

    def mknod_op(self, where, what):
        args = MKNOD3args(where, what)
        return nfs_argop3(argop=NFSPROC3_MKNOD, opmknod=args)

    def remove_op(self, object):
        args = REMOVE3args(object)
        return nfs_argop3(argop=NFSPROC3_REMOVE, opremove=args)

    def rmdir_op(self, object):
        args = RMDIR3args(object)
        return nfs_argop3(argop=NFSPROC3_RMDIR, oprmdir=args)

    def rename_op(self, fromfile, tofile):
        args = RENAME3args(fromfile, tofile)
        return nfs_argop3(argop=NFSPROC3_RENAME, oprename=args)

    def link_op(self, file, link):
        args = LINK3args(file, link)
        return nfs_argop3(argop=NFSPROC3_LINK, oplink=args)

    def readdir_op(self, dir, cookie, cookieverf, count):
        args = READDIR3args(dir, cookie, cookieverf, count)
        return nfs_argop3(argop=NFSPROC3_READDIR, opreaddir=args)

    def readdirplus_op(self, dir, cookie, cookieverf, dircount, maxcount):
        args = READDIRPLUS3args(dir, cookie, cookieverf, dircount, maxcount)
        return nfs_argop3(argop=NFSPROC3_READDIRPLUS, opreaddirplus=args)

    def fsstat_op(self, fsroot):
        args = FSSTAT3args(fsroot)
        return nfs_argop3(argop=NFSPROC3_FSSTAT, opfsstat=args)

    def fsinfo_op(self):
        return nfs_argop3(argop=NFSPROC3_FSINFO)

    def pathconf_op(self, object):
        args = PATHCONF3args(object)
        return nfs_argop3(argop=NFSPROC3_PATHCONF, oppathconf=args)

    def commit_op(self, file, offset, count):
        args = COMMIT3args(file, offset, count)
        return nfs_argop3(argop=NFSPROC3_COMMIT, opcommit=args)
