# Generated by rpcgen.py from /root/work/src/stolaxy/6nov/stolaxy/pynfs/nfs4.1/xdrdef/portmap.x on Wed Nov 12 13:54:47 2014
PMAPPROC_SET = 1
PMAPPROC_NULL = 0
PMAPPROC_DUMP = 4
PMAPPROC_GETPORT = 3
PMAPPROC_CALLIT = 5
PMAPPROC_UNSET = 2
PMAP_PORT = 111
IPPROTO_TCP = 6
IPPROTO_UDP = 17
PMAP_PROG = 100000
PMAP_VERS = 2
