ELECTION_TIMEOUT = 10000 #milli seconds
ELECTION_TIMEOUT_SECONDS = ELECTION_TIMEOUT/1000
RPC_FAILURE_BACKOFF_MS = 10
HEARTBEAT_PERIOD_SECONDS=5
FOLLOWER = 0
CANDIDATE = 1
LEADER = 2

BLANK=0
STABLE=1
STAGING=2
TRANSITIONAL=3

etype = {1:'CONFIGURATION', 2:'DATA', 3:'NOOP'}

MAX_ENTRIES = 128
